export const CONNECT_WEBSOCKET = 'CONNECT_WEBSOCKET';
export const DISCONNECT_WEBSOCKET = 'DISCONNECT_WEBSOCKET';

export const NEW_MESSAGE = 'NEW_MESSAGE';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const JOINING_MESSAGE = 'JOINING_MESSAGE';
export const FETCH_MESSAGE = 'FETCH_MESSAGE';

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const FETCH_NOTIFICATION = 'FETCH_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
export const ACCEPT_INVITE_REQUEST = 'ACCEPT_INVITE_REQUEST';
export const DENY_INVITE_REQUEST = 'DENY_INVITE_REQUEST';


export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const FETCH_USERS = 'FETCH_USERS';
export const FRIENDING_REQUEST = 'FRIENDING_REQUEST';

export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';

export const INVITE_REQUEST = 'INVITE_REQUEST';
export const ADD_NEW_REQUEST = 'ADD_NEW_REQUEST';
export const REFRESH_REQUEST = 'REFRESH_REQUEST';

export const FETCH_ROOMS = 'FETCH_ROOMS';
export const GET_ROOM = 'GET_ROOM';
export const UPDATE_ROOM = 'UPDATE_ROOM';

// Status actions
export const CREATE_ROOM_STATUS = 'CREATE_ROOM_STATUS';

// Window actions
export const UPDATE_WINDOW_SIZE = 'UPDATE_WINDOW_SIZE';





